### ISSUE TITLE
ScriptHandler must configure ``secret_key``

### ISSUE THREAD

**Issue by eric-chau** [backbee/ComposerHandler#1]
BackBee Security component needs this value to start properly. This value must be setted in ``services.yml`` files

**Comment by mickaelandrieu** [comment]
In the distributed zip file we can add already filled ``services.yml`` file, in the repository we can also use a Composer script Handler to manipulate a Yaml file (see Yaml component from Symfony if you want to write yaml on a file)

**Comment by eric-chau** [comment]
This is what i wanted to mean and to do, but i create this issue to be sure I won't forget it =)
